version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: notes-mongodb-prod
    restart: always
    volumes:
      - mongo-data-prod:/data/db
    networks:
      - notes-network

  backend:
    image: ash1204/notes-backend:latest
    container_name: notes-backend-prod
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://mongodb:27017/notesdb
      - NODE_ENV=production
      - JWT_SECRET=thisissecretkeyforjwt
      - JWT_EXPIRE=7d

    depends_on:
      - mongodb
    networks:
      - notes-network
    restart: always

  frontend:
    image: ash1204/notes-frontend:latest
    container_name: notes-frontend-prod
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - notes-network
    restart: always

networks:
  notes-network:
    driver: bridge

volumes:
  mongo-data-prod: